### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found

### ISSUE THREAD

**Issue by jpage4500** [TGX-Android/tdlib#5]
Hi, first off I really appreciate that you guys are maintaining this prebuilt library. The official TDLib one hasn't been updated in years!

Also, I know you said this isn't designed to work with other apps too: `This bundle is not intended to be used in any projects except Telegram X. Moreover, it might include unstable/work-in-progress features and changes, which may lead to an unexpected behavior of any kind.`

That said, I did try using this library in an Android app and ran into the following crash when it was loaded. Is this something you've seen before?

```
10-13 09:58:26.763	com.research.telegram	21451	21560	W	System.err	 java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found: needed by /data/app/~~r4MAve3ocxlDjqT31LTeFw==/com.research.telegram-FH9jY3wTmFDVHWbtcDmotg==/lib/arm64/libtdjni.so in namespace classloader-namespace	
10-13 09:58:26.763	com.research.telegram	21451	21560	W	System.err	 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)	
10-13 09:58:26.763	com.research.telegram	21451	21560	W	System.err	 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)	
10-13 09:58:26.763	com.research.telegram	21451	21560	W	System.err	 	at java.lang.System.loadLibrary(System.java:1661)	
10-13 09:58:26.763	com.research.telegram	21451	21560	W	System.err	 	at org.drinkless.tdlib.Client.<clinit>(Client.java:18)	
```

```
10-13 09:58:26.763	com.research.telegram	21451	21560	E	com.research.telegram	 No implementation found for int org.drinkless.tdlib.Client.createNativeClient() (tried Java_org_drinkless_tdlib_Client_createNativeClient and Java_org_drinkless_tdlib_Client_createNativeClient__)	
10-13 09:58:26.764	com.research.telegram	21451	21560	E	EventBus	 Could not dispatch event: class com.research.telegram.api.events.DeviceEvents$ListenerPermissionsChangedEvent to subscribing class class com.research.telegram.manager.TelegramSDKManager	
10-13 09:58:26.764	com.research.telegram	21451	21560	E	EventBus	 java.lang.UnsatisfiedLinkError: No implementation found for int org.drinkless.tdlib.Client.createNativeClient() (tried Java_org_drinkless_tdlib_Client_createNativeClient and Java_org_drinkless_tdlib_Client_createNativeClient__)	
10-13 09:58:26.764	com.research.telegram	21451	21560	E	EventBus	 	at org.drinkless.tdlib.Client.createNativeClient(Native Method)	
10-13 09:58:26.764	com.research.telegram	21451	21560	E	EventBus	 	at org.drinkless.tdlib.Client.<init>(Client.java:218)	
10-13 09:58:26.764	com.research.telegram	21451	21560	E	EventBus	 	at org.drinkless.tdlib.Client.create(Client.java:118)	
```

**Comment by vkryl** [comment]
This happens because the binaries in this repository rely on shared C++ Runtime, which intentionally isn't tracked into this repository.

The simplest way around this (enough for research purposes) is to extract `c++_shared.so` from the NDK bundle (`$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/$HOST_ARCH/sysroot/usr/lib/$FULL_ABI/libc++_shared.so`), put it in your project's shared libraries folder and load it before loading TDLib library. Everything will start working properly afterwards.

Just make sure NDK bundle version matches the NDK version set in [version.properties](https://github.com/TGX-Android/Telegram-X/blob/main/version.properties) (`version.ndk_primary` and `version.ndk_legacy`), which is currently `23.2.8568313`, but might change at any point in future.
